//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETA_TALLER.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GETA_factura
    {
        public int id_factura { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
        public Nullable<double> ITB { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public Nullable<int> id_mecanico { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_taller { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public string PAGO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> detalle { get; set; }
        public Nullable<int> id_inventario { get; set; }
        public Nullable<int> id_detalle { get; set; }
    
        public virtual GETA_cliente GETA_cliente { get; set; }
        public virtual GETA_detalle_reparacion GETA_detalle_reparacion { get; set; }
        public virtual GETA_inventario_repuesto GETA_inventario_repuesto { get; set; }
        public virtual GETA_mecanico GETA_mecanico { get; set; }
        public virtual GETA_taller GETA_taller { get; set; }
        public virtual GETA_vehiculo GETA_vehiculo { get; set; }
    }
}
