//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETA_TALLER.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GETA_mecanico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GETA_mecanico()
        {
            this.GETA_detalle_reparacion = new HashSet<GETA_detalle_reparacion>();
            this.GETA_factura = new HashSet<GETA_factura>();
            this.GETA_usuario = new HashSet<GETA_usuario>();
        }
    
        public int id_mecanico { get; set; }
        public string NOMBRE { get; set; }
        public string APELLID0 { get; set; }
        public string CEDULA { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> id_detalle { get; set; }
        public Nullable<int> ELIMINAR { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_detalle_reparacion> GETA_detalle_reparacion { get; set; }
        public virtual GETA_detalle_reparacion GETA_detalle_reparacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_factura> GETA_factura { get; set; }
        public virtual GETA_vehiculo GETA_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_usuario> GETA_usuario { get; set; }
    }
}
