//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETA_TALLER.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GETA_servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GETA_servicio()
        {
            this.GETA_detalle_reparacion = new HashSet<GETA_detalle_reparacion>();
        }
    
        public int id_servicio { get; set; }
        public string EVALUCION { get; set; }
        public Nullable<int> PRECIO { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_detalle_reparacion> GETA_detalle_reparacion { get; set; }
        public virtual GETA_vehiculo GETA_vehiculo { get; set; }
    }
}
