//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETA_TALLER.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GETA_inventario_repuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GETA_inventario_repuesto()
        {
            this.GETA_detalle_reparacion = new HashSet<GETA_detalle_reparacion>();
            this.GETA_factura = new HashSet<GETA_factura>();
        }
    
        public int id_inventario { get; set; }
        public string CATEGORIA { get; set; }
        public string NOMBRE_PIEZAS { get; set; }
        public Nullable<int> CANTIDAD_DISPONIBLE { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> id_detalle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_detalle_reparacion> GETA_detalle_reparacion { get; set; }
        public virtual GETA_detalle_reparacion GETA_detalle_reparacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_factura> GETA_factura { get; set; }
    }
}
