//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETA_TALLER.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GETA_usuario
    {
        public int id_usuario { get; set; }
        public Nullable<int> ROL { get; set; }
        public string NOMBRE { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public Nullable<int> id_mecanico { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual GETA_mecanico GETA_mecanico { get; set; }
    }
}
