//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETA_TALLER.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GETA_detalle_reparacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GETA_detalle_reparacion()
        {
            this.GETA_factura = new HashSet<GETA_factura>();
            this.GETA_inventario_repuesto1 = new HashSet<GETA_inventario_repuesto>();
            this.GETA_mecanico1 = new HashSet<GETA_mecanico>();
        }
    
        public int id_detalle { get; set; }
        public string CANTIDAD { get; set; }
        public Nullable<double> MANO_OBRA { get; set; }
        public string COMETARIO { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<int> id_inventario { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> id_mecanico { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
    
        public virtual GETA_inventario_repuesto GETA_inventario_repuesto { get; set; }
        public virtual GETA_mecanico GETA_mecanico { get; set; }
        public virtual GETA_servicio GETA_servicio { get; set; }
        public virtual GETA_vehiculo GETA_vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_factura> GETA_factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_inventario_repuesto> GETA_inventario_repuesto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_mecanico> GETA_mecanico1 { get; set; }
    }
}
