//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETA_TALLER.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GETA_vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GETA_vehiculo()
        {
            this.GETA_detalle_reparacion = new HashSet<GETA_detalle_reparacion>();
            this.GETA_factura = new HashSet<GETA_factura>();
            this.GETA_mecanico = new HashSet<GETA_mecanico>();
            this.GETA_servicio = new HashSet<GETA_servicio>();
        }
    
        public int id_vehiculo { get; set; }
        public string MATRICULA { get; set; }
        public string MODELO { get; set; }
        public string COLOR { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual GETA_cliente GETA_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_detalle_reparacion> GETA_detalle_reparacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_factura> GETA_factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_mecanico> GETA_mecanico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETA_servicio> GETA_servicio { get; set; }
    }
}
