//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETA_TALLER.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GETA_tallerEntities4 : DbContext
    {
        public GETA_tallerEntities4()
            : base("name=GETA_tallerEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GETA_cliente> GETA_cliente { get; set; }
        public virtual DbSet<GETA_detalle_reparacion> GETA_detalle_reparacion { get; set; }
        public virtual DbSet<GETA_factura> GETA_factura { get; set; }
        public virtual DbSet<GETA_inventario_repuesto> GETA_inventario_repuesto { get; set; }
        public virtual DbSet<GETA_mecanico> GETA_mecanico { get; set; }
        public virtual DbSet<GETA_servicio> GETA_servicio { get; set; }
        public virtual DbSet<GETA_taller> GETA_taller { get; set; }
        public virtual DbSet<GETA_usuario> GETA_usuario { get; set; }
        public virtual DbSet<GETA_vehiculo> GETA_vehiculo { get; set; }
    
        public virtual ObjectResult<detalle_factura_Result> detalle_factura(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<detalle_factura_Result>("detalle_factura", id_clienteParameter);
        }
    
        public virtual ObjectResult<detalle_factura1_Result> detalle_factura1(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<detalle_factura1_Result>("detalle_factura1", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_Result> factura(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_Result>("factura", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalle_Result> factura_detalle(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle_Result>("factura_detalle", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalle1_Result> factura_detalle1(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle1_Result>("factura_detalle1", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalle10_Result> factura_detalle10(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle10_Result>("factura_detalle10", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalle11_Result> factura_detalle11(Nullable<int> id_cliente, Nullable<int> id_mecanico)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var id_mecanicoParameter = id_mecanico.HasValue ?
                new ObjectParameter("id_mecanico", id_mecanico) :
                new ObjectParameter("id_mecanico", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle11_Result>("factura_detalle11", id_clienteParameter, id_mecanicoParameter);
        }
    
        public virtual ObjectResult<factura_detalle2_Result> factura_detalle2(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle2_Result>("factura_detalle2", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalle3_Result> factura_detalle3(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle3_Result>("factura_detalle3", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalle4_Result> factura_detalle4(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle4_Result>("factura_detalle4", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalle5_Result> factura_detalle5(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle5_Result>("factura_detalle5", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalle6_Result> factura_detalle6(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle6_Result>("factura_detalle6", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalle7_Result> factura_detalle7(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle7_Result>("factura_detalle7", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalle8_Result> factura_detalle8(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle8_Result>("factura_detalle8", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalle9_Result> factura_detalle9(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalle9_Result>("factura_detalle9", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalleA1_Result> factura_detalleA1(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalleA1_Result>("factura_detalleA1", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalleA2_Result> factura_detalleA2(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalleA2_Result>("factura_detalleA2", id_clienteParameter);
        }
    
        public virtual ObjectResult<factura_detalleA3_Result> factura_detalleA3(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_detalleA3_Result>("factura_detalleA3", id_clienteParameter);
        }
    
        public virtual ObjectResult<id_mecanico_Result> id_mecanico(Nullable<int> id_cliente, Nullable<int> id_mecanico)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var id_mecanicoParameter = id_mecanico.HasValue ?
                new ObjectParameter("id_mecanico", id_mecanico) :
                new ObjectParameter("id_mecanico", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<id_mecanico_Result>("id_mecanico", id_clienteParameter, id_mecanicoParameter);
        }
    
        public virtual ObjectResult<proceso_factura_Result> proceso_factura(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proceso_factura_Result>("proceso_factura", id_clienteParameter);
        }
    
        public virtual ObjectResult<proceso_factura1_Result> proceso_factura1(Nullable<double> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proceso_factura1_Result>("proceso_factura1", id_clienteParameter);
        }
    }
}
